"""Rift v0.1 — Compiler.
Takes a validated RiftValidator IR dict and emits a Pi Script (.pi) source string.

Usage:
    python -m rift.compiler <file.rift> [output.pi]
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any


# ── Name utilities ─────────────────────────────────────────────────────────────

def _to_pascal(name: str) -> str:
    """snake_id or lowercase → PascalCase."""
    return "".join(part.capitalize() for part in name.split("_"))


def _map_name_for(state_value: str, used: set[str]) -> str:
    """Synthesize a unique PASCAL_ID for a Pi Script map block from a state value."""
    base = _to_pascal(state_value) + "Map"
    if base not in used:
        used.add(base)
        return base
    i = 2
    while f"{base}{i}" in used:
        i += 1
    candidate = f"{base}{i}"
    used.add(candidate)
    return candidate


def _normalize_entity(raw: str) -> str:
    """Ensure entity name is PascalCase for Pi Script state_ref."""
    return _to_pascal(raw)


# ── Emitters ──────────────────────────────────────────────────────────────────

def _emit_header(source_name: str) -> str:
    return (
        f"// Generated by Rift v0.1 compiler\n"
        f"// Source: {source_name}\n"
        f"// Do not edit — regenerate from source."
    )


def _emit_domain() -> str:
    return (
        "domain rift_generated {\n"
        "    audit_interval: 1 hour\n"
        "    tiebreaker:     timestamp_asc\n"
        "}"
    )


def _emit_entities(maps: list[dict]) -> str:
    """Infer entity declarations from map targets. Field type is always text."""
    seen: dict[str, set[str]] = {}  # pascal_entity -> {field, ...}
    for m in maps:
        entity = _normalize_entity(m["target_entity"] or "")
        field  = m["target_field"] or ""
        if entity and field:
            seen.setdefault(entity, set()).add(field)

    blocks = []
    for entity in sorted(seen):
        fields_str = "\n".join(
            f"    {field}: text" for field in sorted(seen[entity])
        )
        blocks.append(f"entity {entity} {{\n{fields_str}\n}}")
    return "\n\n".join(blocks)


def _emit_maps(maps: list[dict]) -> str:
    """Emit a Pi Script map block for each Rift map declaration."""
    used_names: set[str] = set()
    blocks = []
    for m in maps:
        entity = _normalize_entity(m["target_entity"] or "")
        field  = m["target_field"] or ""
        value  = m["state_value"] or ""
        pattern = m["pattern"] or ""

        name = _map_name_for(value, used_names)
        blocks.append(
            f"map {name} {{\n"
            f'    target:   {entity}.{field}\n'
            f'    maps_to:  "{value}"\n'
            f'    triggers: ["{pattern}"]\n'
            f"}}"
        )
    return "\n\n".join(blocks)


def _emit_intent_constraint(
    intent_name: str,
    rec: dict,
    maps: list[dict],
) -> str | None:
    """Emit a Pi Script constraint block for an intent's generates clause."""
    generates = rec.get("generates")
    if not generates:
        return None

    treat = rec.get("treat") or {}
    state_value = treat.get("as") or ""
    priority    = rec.get("priority") or "medium"

    # Find the map that declares this state value to get entity + field
    entity = field = ""
    for m in maps:
        if m["state_value"] == state_value:
            entity = _normalize_entity(m["target_entity"] or "")
            field  = m["target_field"] or ""
            break

    if not entity or not field:
        # Cannot form a rule — emit constraint with a placeholder comment
        return (
            f"constraint {generates} {{\n"
            f"    priority:     {priority}\n"
            f"    // WARNING: no matching map found for state '{state_value}'\n"
            f"    on_violation: escalate\n"
            f"}}"
        )

    return (
        f"constraint {generates} {{\n"
        f"    priority:     {priority}\n"
        f'    rule:         {entity}.{field} must equal "{state_value}"\n'
        f"    on_violation: escalate\n"
        f"}}"
    )


def _emit_handwritten_constraint(name: str, rec: dict) -> str:
    """Emit a hand-written Rift constraint_decl as a Pi Script constraint block."""
    lines = [f"constraint {name} {{"]
    if rec.get("priority"):
        lines.append(f"    priority:     {rec['priority']}")
    if rec.get("rule"):
        lines.append(f"    rule:         {rec['rule']}")
    if rec.get("on_violation"):
        actions = " + ".join(rec["on_violation"])
        lines.append(f"    on_violation: {actions}")
    lines.append("}")
    return "\n".join(lines)


def _emit_constraints(ir: dict) -> str:
    blocks = []

    # Generated constraints from intents
    for iname, irec in ir["intents"].items():
        block = _emit_intent_constraint(iname, irec, ir["maps"])
        if block:
            blocks.append(block)

    # Hand-written constraint blocks
    for cname, crec in ir["constraints"].items():
        blocks.append(_emit_handwritten_constraint(cname, crec))

    return "\n\n".join(blocks)


def _emit_enforce(ir: dict) -> str:
    """Emit one enforce block per entity, listing all constraints that apply to it."""
    # Map constraint_name → entity (from the intent's generates + matching map)
    entity_constraints: dict[str, list[str]] = {}

    for irec in ir["intents"].values():
        generates   = irec.get("generates")
        treat       = irec.get("treat") or {}
        state_value = treat.get("as") or ""
        if not generates:
            continue
        entity = ""
        for m in ir["maps"]:
            if m["state_value"] == state_value:
                entity = _normalize_entity(m["target_entity"] or "")
                break
        if entity:
            entity_constraints.setdefault(entity, []).append(generates)

    if not entity_constraints:
        return ""

    blocks = []
    for entity in sorted(entity_constraints):
        names = entity_constraints[entity]
        names_str = ", ".join(names)
        blocks.append(
            f"enforce {{\n"
            f"    entity:      {entity}\n"
            f"    constraints: [{names_str}]\n"
            f"}}"
        )
    return "\n\n".join(blocks)


# ── Compiler ──────────────────────────────────────────────────────────────────

class RiftCompiler:

    def __init__(self, ir: dict[str, Any], source_name: str = "<rift>"):
        self.ir = ir
        self.source_name = source_name

    def compile(self) -> str:
        parts = [
            _emit_header(self.source_name),
            _emit_domain(),
            _emit_entities(self.ir["maps"]),
            _emit_maps(self.ir["maps"]),
            _emit_constraints(self.ir),
            _emit_enforce(self.ir),
        ]
        return "\n\n".join(p for p in parts if p.strip()) + "\n"


# ── CLI ───────────────────────────────────────────────────────────────────────

def compile_file(rift_path: str, output_path: str | None = None) -> tuple[bool, str]:
    """Compile a .rift file to Pi Script. Returns (success, message)."""
    from rift.validator import validate_file

    ok, errors, ir = validate_file(rift_path)
    if not ok:
        return False, "\n".join(f"ERROR  {e}" for e in errors)

    source_name = Path(rift_path).name
    pi_source = RiftCompiler(ir, source_name).compile()

    if output_path is None:
        output_path = str(Path(rift_path).with_suffix(".pi"))

    Path(output_path).write_text(pi_source, encoding="utf-8")
    return True, output_path


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python -m rift.compiler <file.rift> [output.pi]", file=sys.stderr)
        sys.exit(1)

    rift_path  = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None

    success, result = compile_file(rift_path, output_path)
    if success:
        print(f"OK  {result}", file=sys.stderr)
    else:
        print(result, file=sys.stderr)
        sys.exit(1)
